### ISSUE TITLE
Makefile:299: recipe for target 'utils/pg2arrow' failed

### ISSUE THREAD

**Issue by shaunstoltz** [heterodb/pg2arrow#11]
gcc  "-DPGSTROM_VERSION=\"2.3\"" -DCPU_ARCH=\"x86_64\" -DPGSHAREDIR=\"/usr/share/postgresql/10\" -DPGSERV_INCLUDEDIR=\"/usr/include/postgresql/10/server\" -DCUDA_INCLUDE_PATH=\"/usr/local/cuda/include\" -DCUDA_BINARY_PATH=\"/usr/local/cuda/bin\" -DCUDA_LIBRARY_PATH=\"/usr/local/cuda/lib64\" -DCUDA_MAXREGCOUNT=128 -DCMD_GPUINFO_PATH=\"/usr/lib/postgresql/10/bin/gpuinfo\" -I /usr/local/cuda/include -L /usr/local/cuda/lib64 ./utils/gpuinfo.c -o utils/gpuinfo -lcuda
gcc -D__PG2ARROW__=1 -D_GNU_SOURCE -g -Wall -I ./src -I ./utils -I /usr/include/postgresql -I /usr/include/postgresql/10/server -L /usr/lib/x86_64-linux-gnu ./utils/pg2arrow.c ./src/arrow_nodes.c ./src/arrow_write.c -o utils/pg2arrow -lpq -lpgcommon -lpgport
./src/arrow_nodes.c: In function 'put_int16_value':
./src/arrow_nodes.c:32:23: warning: implicit declaration of function 'pg_ntoh16' [-Wimplicit-function-declaration]
 #define __ntoh16(x)   pg_ntoh16(x)
                       ^
./src/arrow_nodes.c:1776:11: note: in expansion of macro '__ntoh16'
   value = __ntoh16(*((const uint16 *)addr));
           ^
./src/arrow_nodes.c: In function 'put_int32_value':
./src/arrow_nodes.c:33:23: warning: implicit declaration of function 'pg_ntoh32' [-Wimplicit-function-declaration]
 #define __ntoh32(x)   pg_ntoh32(x)
                       ^
./src/arrow_nodes.c:1795:11: note: in expansion of macro '__ntoh32'
   value = __ntoh32(*((const uint32 *)addr));
           ^
./src/arrow_nodes.c: In function 'put_int64_value':
./src/arrow_nodes.c:34:23: warning: implicit declaration of function 'pg_ntoh64' [-Wimplicit-function-declaration]
 #define __ntoh64(x)   pg_ntoh64(x)
                       ^
./src/arrow_nodes.c:1814:11: note: in expansion of macro '__ntoh64'
   value = __ntoh64(*((const uint64 *)addr));
           ^
./src/arrow_nodes.c: In function '__put_date_value_generic':
./src/arrow_nodes.c:2042:13: error: 'POSTGRES_EPOCH_JDATE' undeclared (first use in this function)
   value += (POSTGRES_EPOCH_JDATE - UNIX_EPOCH_JDATE);
             ^
./src/arrow_nodes.c:2042:13: note: each undeclared identifier is reported only once for each function it appears in
./src/arrow_nodes.c:2042:36: error: 'UNIX_EPOCH_JDATE' undeclared (first use in this function)
   value += (POSTGRES_EPOCH_JDATE - UNIX_EPOCH_JDATE);
                                    ^
./src/arrow_nodes.c: In function '__put_timestamp_value_generic':
./src/arrow_nodes.c:2187:2: error: unknown type name 'Timestamp'
  Timestamp value;
  ^
In file included from ./src/arrow_ipc.h:20:0,
                 from ./src/arrow_nodes.c:36:
./src/arrow_nodes.c:2193:29: error: 'Timestamp' undeclared (first use in this function)
   assert(pgsql_sz == sizeof(Timestamp));
                             ^
./src/arrow_nodes.c:2194:29: error: expected ')' before 'Timestamp'
   value = __ntoh64(*((const Timestamp *)addr));
                             ^
./src/arrow_nodes.c:34:33: note: in definition of macro '__ntoh64'
 #define __ntoh64(x)   pg_ntoh64(x)
                                 ^
./src/arrow_nodes.c:2194:3: warning: type defaults to 'int' in type name [-Wimplicit-int]
   value = __ntoh64(*((const Timestamp *)addr));
   ^
./src/arrow_nodes.c:2194:22: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   value = __ntoh64(*((const Timestamp *)addr));
                      ^
./src/arrow_nodes.c:34:33: note: in definition of macro '__ntoh64'
 #define __ntoh64(x)   pg_ntoh64(x)
                                 ^
./src/arrow_nodes.c:2194:20: error: invalid type argument of unary '*' (have 'int')
   value = __ntoh64(*((const Timestamp *)addr));
                    ^
./src/arrow_nodes.c:34:33: note: in definition of macro '__ntoh64'
 #define __ntoh64(x)   pg_ntoh64(x)
                                 ^
./src/arrow_nodes.c:2196:13: error: 'POSTGRES_EPOCH_JDATE' undeclared (first use in this function)
   value += (POSTGRES_EPOCH_JDATE -
             ^
./src/arrow_nodes.c:2197:7: error: 'UNIX_EPOCH_JDATE' undeclared (first use in this function)
       UNIX_EPOCH_JDATE) * USECS_PER_DAY;
       ^
./src/arrow_nodes.c:2197:27: error: 'USECS_PER_DAY' undeclared (first use in this function)
       UNIX_EPOCH_JDATE) * USECS_PER_DAY;
                           ^
In file included from ./src/arrow_ipc.h:20:0,
                 from ./src/arrow_nodes.c:36:
./src/arrow_nodes.c: In function '__put_interval_year_month_value':
./src/arrow_nodes.c:2278:23: error: 'Interval' undeclared (first use in this function)
   assert(sz == sizeof(Interval));
                       ^
./src/arrow_nodes.c:2279:24: error: expected ')' before 'Interval'
   m = __ntoh32(((const Interval *)addr)->month);
                        ^
./src/arrow_nodes.c:33:33: note: in definition of macro '__ntoh32'
 #define __ntoh32(x)   pg_ntoh32(x)
                                 ^
./src/arrow_nodes.c:2279:3: warning: type defaults to 'int' in type name [-Wimplicit-int]
   m = __ntoh32(((const Interval *)addr)->month);
   ^
./src/arrow_nodes.c:2279:17: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   m = __ntoh32(((const Interval *)addr)->month);
                 ^
./src/arrow_nodes.c:33:33: note: in definition of macro '__ntoh32'
 #define __ntoh32(x)   pg_ntoh32(x)
                                 ^
./src/arrow_nodes.c:2279:40: error: invalid type argument of '->' (have 'int')
   m = __ntoh32(((const Interval *)addr)->month);
                                        ^
./src/arrow_nodes.c:33:33: note: in definition of macro '__ntoh32'
 #define __ntoh32(x)   pg_ntoh32(x)
                                 ^
./src/arrow_nodes.c: In function '__put_interval_day_time_value':
./src/arrow_nodes.c:2293:3: error: unknown type name 'Interval'
   Interval iv;
   ^
In file included from ./src/arrow_ipc.h:20:0,
                 from ./src/arrow_nodes.c:36:
./src/arrow_nodes.c:2296:23: error: 'Interval' undeclared (first use in this function)
   assert(sz == sizeof(Interval));
                       ^
./src/arrow_nodes.c:2297:5: error: request for member 'time' in something not a structure or union
   iv.time  = __ntoh64(((const Interval *)addr)->time);
     ^
./src/arrow_nodes.c:2297:31: error: expected ')' before 'Interval'
   iv.time  = __ntoh64(((const Interval *)addr)->time);
                               ^
./src/arrow_nodes.c:34:33: note: in definition of macro '__ntoh64'
 #define __ntoh64(x)   pg_ntoh64(x)
                                 ^
./src/arrow_nodes.c:2297:3: warning: type defaults to 'int' in type name [-Wimplicit-int]
   iv.time  = __ntoh64(((const Interval *)addr)->time);
   ^
./src/arrow_nodes.c:2297:24: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   iv.time  = __ntoh64(((const Interval *)addr)->time);
                        ^
./src/arrow_nodes.c:34:33: note: in definition of macro '__ntoh64'
 #define __ntoh64(x)   pg_ntoh64(x)
                                 ^
./src/arrow_nodes.c:2297:47: error: invalid type argument of '->' (have 'int')
   iv.time  = __ntoh64(((const Interval *)addr)->time);
                                               ^
./src/arrow_nodes.c:34:33: note: in definition of macro '__ntoh64'
 #define __ntoh64(x)   pg_ntoh64(x)
                                 ^
./src/arrow_nodes.c:2298:5: error: request for member 'day' in something not a structure or union
   iv.day   = __ntoh32(((const Interval *)addr)->day);
     ^
./src/arrow_nodes.c:2298:31: error: expected ')' before 'Interval'
   iv.day   = __ntoh32(((const Interval *)addr)->day);
                               ^
./src/arrow_nodes.c:33:33: note: in definition of macro '__ntoh32'
 #define __ntoh32(x)   pg_ntoh32(x)
                                 ^
./src/arrow_nodes.c:2298:3: warning: type defaults to 'int' in type name [-Wimplicit-int]
   iv.day   = __ntoh32(((const Interval *)addr)->day);
   ^
./src/arrow_nodes.c:2298:24: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   iv.day   = __ntoh32(((const Interval *)addr)->day);
                        ^
./src/arrow_nodes.c:33:33: note: in definition of macro '__ntoh32'
 #define __ntoh32(x)   pg_ntoh32(x)
                                 ^
./src/arrow_nodes.c:2298:47: error: invalid type argument of '->' (have 'int')
   iv.day   = __ntoh32(((const Interval *)addr)->day);
                                               ^
./src/arrow_nodes.c:33:33: note: in definition of macro '__ntoh32'
 #define __ntoh32(x)   pg_ntoh32(x)
                                 ^
./src/arrow_nodes.c:2299:5: error: request for member 'month' in something not a structure or union
   iv.month = __ntoh32(((const Interval *)addr)->month);
     ^
./src/arrow_nodes.c:2299:31: error: expected ')' before 'Interval'
   iv.month = __ntoh32(((const Interval *)addr)->month);
                               ^
./src/arrow_nodes.c:33:33: note: in definition of macro '__ntoh32'
 #define __ntoh32(x)   pg_ntoh32(x)
                                 ^
./src/arrow_nodes.c:2299:3: warning: type defaults to 'int' in type name [-Wimplicit-int]
   iv.month = __ntoh32(((const Interval *)addr)->month);
   ^
./src/arrow_nodes.c:2299:24: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   iv.month = __ntoh32(((const Interval *)addr)->month);
                        ^
./src/arrow_nodes.c:33:33: note: in definition of macro '__ntoh32'
 #define __ntoh32(x)   pg_ntoh32(x)
                                 ^
./src/arrow_nodes.c:2299:47: error: invalid type argument of '->' (have 'int')
   iv.month = __ntoh32(((const Interval *)addr)->month);
                                               ^
./src/arrow_nodes.c:33:33: note: in definition of macro '__ntoh32'
 #define __ntoh32(x)   pg_ntoh32(x)
                                 ^
./src/arrow_nodes.c:2306:13: error: request for member 'month' in something not a structure or union
   value = iv.month + DAYS_PER_MONTH * iv.day;
             ^
./src/arrow_nodes.c:2306:41: error: request for member 'day' in something not a structure or union
   value = iv.month + DAYS_PER_MONTH * iv.day;
                                         ^
./src/arrow_nodes.c:2308:13: error: request for member 'time' in something not a structure or union
   value = iv.time / 1000;
             ^
./src/arrow_nodes.c:2293:12: warning: variable 'iv' set but not used [-Wunused-but-set-variable]
   Interval iv;
            ^
Makefile:299: recipe for target 'utils/pg2arrow' failed
make: *** [utils/pg2arrow] Error 1
The command '/bin/sh -c git clone https://github.com/heterodb/pg-strom.git pg_strom && cd pg_strom && make PG_CONFIG=/usr/bin/pg_config' returned a non-zero code: 2

**Comment by kaigai** [comment]
Hmm... `pg_ntohXX()` was not defined at PG10. Needs to be fixed.

**Comment by shaunstoltz** [comment]
OK, best suggestion to move up to PG11?

**Comment by kaigai** [comment]
If you can wait for tomorrow, stay PG10. :)

**Comment by shaunstoltz** [comment]
OK, I bumped to PG11 and getting the issue #6 errors:
/usr/bin/ld: cannot find -lpgcommon
/usr/bin/ld: cannot find -lpgport

Can wait till tomorrow.. :0)

Thanks!
S

**Comment by kaigai** [comment]
3e51dc224eef15c4d2f7a4f0fe10d01b52c47695 fixed this problem.
Thanks for your report.
