### ISSUE TITLE
Invalid arrow file generated

### ISSUE THREAD

**Issue by alexkreidler** [heterodb/pg2arrow#14]
I've generated an arrow file from a query returning 10 rows.

Then when I try to read it in NodeJS with the official JS library, I get: `Error: Expected to read 1836017711 metadata bytes, but only read 32.` When I try to read it with `pyarrow` in Python, I get `OSError: Unexpected null field Field.type in flatbuffer-encoded metadata`. I've also tried opening it with the Data Preview extension in VSCode (`randomfractalsinc.vscode-data-preview`).

It seems like the generated metadata is just invalid, which maybe makes sense because the last commit was 2 years 10 months ago.

I understand that the project is [no longer updated](https://github.com/heterodb/pg2arrow/issues/10#issuecomment-561645700) and [alternatives approaches are recommended](http://heterodb.github.io/pg-strom/arrow_fdw/#how-to-make-arrow-files). But I'll leave this issue here to help others if they come along.

**Comment by kaigai** [comment]
This project outcome was already merged to `pg-strom`.
https://github.com/heterodb/pg-strom/tree/master/arrow-tools

Because its code base is also used to `arrow_fdw`, `pcap2arrow` and `fluent-plugin-arrow-file`, not only `pg2arrow`.
Please don't refer this old repository.

I'll make this `heterodb/pg2arrow` non-public mode in a few days.

**Comment by alexkreidler** [comment]
OK, I see, awesome! https://github.com/heterodb/pg-strom/blob/master/arrow-tools/sql2arrow.c

I think if you add a note on the README linking to there, and archive this repository, that would be best, because some other projects link to this repository `heterodb/pg2arrow` (e.g. https://github.com/psycopg/psycopg2/issues/1058) and it would be good to keep this public so people can find the right place. 

Thanks for your work!
