### ISSUE TITLE
When the username option is not specified, the permission of the output file becomes illegal.

### ISSUE THREAD

**Issue by nuko-yokohama** [heterodb/pg2arrow#5]
When the username option is not specified, the access right of the output file becomes illegal.

There is no problem if you explicitly specify the "-U username" option.
```
$ ./pg2arrow -U nuko -c "SELECT * FROM sample2" -d sample -o out.data
$ ls -l out.data
-rw-rwx--T. 1 nuko nuko 718  1月 21 19:20 out.data
```

If you do not specify the username option, the access rights of the generated output file are not valid.
```
$ ./pg2arrow -c "SELECT * FROM sample2" -d sample -o out.data
$ ls -l out.data
--w---S--T. 1 nuko nuko 718  1月 21 19:20 out.data
```

**Comment by kaigai** [comment]
Thanks for your report. It was fixed at 2117176fe8a1e0fa31936213a6bd5b798592290a

Prior implementation relies on default setting on open(2) with O_CREAT.
This patch adds `0644` as file access mode on creation. If read permission on group/other are not needed, we can mask them by `umask`.

```
$ ./pg2arrow postgres -c "SELECT * FROM test5" -o /tmp/capybara
$ ls -l /tmp/capybara
-rw-r--r--. 1 kaigai users 19838 Jan 22 13:43 /tmp/capybara
```
